# Site setings
name: "Anomitra's Blog"
description: 'I write about tech, movies, music, crazy ideas, and anything else that catches my fancy.'
meta_description: ''
#logo: 'assets/images/logo.png'
logo: 'assets/images/header.png'
favicon: 'assets/images/favicon.ico'
production_url: https://anomitra.github.io
disqus: 'anomitra-me'
mailchimp_url: ''
cover_image: bc_1.jpg
# Add your GA Tracking Id
# ga_analytics: UA-49980823-11


# Author
author:
  name: 'Anomitra Saha'
  image: 'blank-headshot.jpg'
  greetings: 'Hi there!'
  description: "I'm a software developer by profession, and I write about tech, movies, music, crazy ideas, and anything else that catches my fancy. Scroll down for some of my recent posts!"
  bio: 'This is a short placeholder for a bio which will be added later.'

# Contact form setings
email: testmail@gmail.com
contact_page_description: "This theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'RickterScale_'
#facebook: 'username'
github: 'anomitra'
#codepen: 'username'
#dribbble: 'username'
instagram: 'anomitra_'
#pinterest: 'username'
linkedin: 'anomitra.saha'
#producthunt: '@username'

# Navigation
navigation:
  - text: About
    url: /about
  - text: Style Guide
    url: /style-guide
  - text: Contact Me
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
